const D = {
  A_FARMERS: 'af',
  A_BUILDERS: 'ab',
  A_WARRIORS: 'aw',
  A_GUARDS: 'ag',
  MAX_SPRITES: 100,
  MAX_MONSTERS: 5,
  MAX_BUILDINGS: 15,
  MIN_MONSTER_SIZE: 5,
  PEOPLE_VEL: 50,
  PEOPLE_MOVE_CD: 1,
  PEOPLE_FARMER_SPAWN_CD: 1,
  PEOPLE_BUILDER_SPAWN_CD: 2,
  PEOPLE_WARRIOR_SPAWN_CD: 3,
  PEOPLE_GUARD_SPAWN_CD: 4,
  P_FD: -1,
  P_BD: -1,
  P_WD: 1,
  P_GD: 5,
  B_CD: 1,
  M_CD: 3,
  M_S: 3,
  M_W: 10,
  W_UP: 'u',
  W_DOWN: 'd',
  W_RIGHT: 'r',
  W_LEFT: 'l',
  STOPPED: 's',
}

export {D}
